import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';

const pkg = JSON.parse(readFileSync('package.json', 'utf-8'));
mkdirSync('src/generated', { recursive: true });
writeFileSync(
  'src/generated/version.ts',
  `// Auto-generated by scripts/generate-version.mjs — do not edit\nexport const VERSION = ${JSON.stringify(pkg.version)} as const;\n`,
);
